version: '3'
services:
  downloader:
    image: alpine:latest
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "apk --no-cache add git && git clone https://github.com/ravens>
  flask_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
