version: '3.9'
services:

  shopping_list:
      env_file:
        - .env
      build: .
      container_name: shopping_list
      ports:
        - "5000:5000"
      restart: unless-stopped
      volumes:
        - /home/ravenstudios/flask_shopping_list/instance:/app/instance
